services:
  modura-api:
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # 개발 환경용 Spring Profile 활성화 (application-dev.yaml 로드)
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_DATABASE}?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD} # healthcheck를 위한 root 비밀번호
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
  nginx:
   ports:
     - "80:80"
   volumes:
     - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql-data: