services:
  modura-api:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - spring-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Nginx 리버스 프록시 서비스
  nginx:
    image: nginx:stable-alpine
    networks:
      - spring-network
    depends_on:
      - modura-api

# 데이터 영속성 보장
volumes:
  redis-data:

networks:
  spring-network:
    driver: bridge