name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Spring Boot JAR && Build the Docker image
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test 
          docker build -t ehyeon/modura-server:latest .

      # 4. Docker Hub 로그인
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push ehyeon/modura-server:latest
